export const countryCodes = [
  { code: "+93", label: "AFG", name: "Afghanistan" },
  { code: "+355", label: "ALB", name: "Albania" },
  { code: "+213", label: "DZA", name: "Algeria" },
  { code: "+376", label: "AND", name: "Andorra" },
  { code: "+244", label: "AGO", name: "Angola" },
  { code: "+1", label: "AIA", name: "Anguilla" },
  { code: "+1", label: "ATG", name: "Antigua and Barbuda" },
  { code: "+54", label: "ARG", name: "Argentina" },
  { code: "+374", label: "ARM", name: "Armenia" },
  { code: "+297", label: "ABW", name: "Aruba" },
  { code: "+61", label: "AUS", name: "Australia" },
  { code: "+43", label: "AUT", name: "Austria" },
  { code: "+994", label: "AZE", name: "Azerbaijan" },
  { code: "+973", label: "BHR", name: "Bahrain" },
  { code: "+880", label: "BGD", name: "Bangladesh" },
  { code: "+32", label: "BEL", name: "Belgium" },
  { code: "+55", label: "BRA", name: "Brazil" },
  { code: "+1", label: "CAN", name: "Canada" },
  { code: "+86", label: "CHN", name: "China" },
  { code: "+20", label: "EGY", name: "Egypt" },
  { code: "+33", label: "FRA", name: "France" },
  { code: "+49", label: "DEU", name: "Germany" },
  { code: "+91", label: "IND", name: "India" },
  { code: "+62", label: "IDN", name: "Indonesia" },
  { code: "+98", label: "IRN", name: "Iran" },
  { code: "+964", label: "IRQ", name: "Iraq" },
  { code: "+39", label: "ITA", name: "Italy" },
  { code: "+81", label: "JPN", name: "Japan" },
  { code: "+92", label: "PAK", name: "Pakistan" },
  { code: "+966", label: "SAU", name: "Saudi Arabia" },
  { code: "+65", label: "SGP", name: "Singapore" },
  { code: "+27", label: "ZAF", name: "South Africa" },
  { code: "+82", label: "KOR", name: "South Korea" },
  { code: "+90", label: "TUR", name: "Türkiye" },
  { code: "+971", label: "ARE", name: "United Arab Emirates" },
  { code: "+44", label: "GBR", name: "United Kingdom" },
  { code: "+1", label: "USA", name: "United States" },
];